name: PlayerGraffiti
version: '3.0.0'
main: fr.sizooo.playergraffiti.Main
api-version: '1.21'
description: Temporary graffiti system for signs with proper character limits
author: Sizooo

commands:
  graffiti:
    description: Main graffiti command - use /graffiti for help
    usage: /graffiti
    aliases: [g, tag]

permissions:
  playergraffiti.use:
    description: Allows using graffiti
    default: true
  playergraffiti.admin:
    description: Allows admin commands
    default: op